server:
  port: 8080
  servlet:
    context-path: /khuongmai

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/khuongmaiapp"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true


jwt:
  signerKey: "SSK9eMPla1BcwJY6df2hHud2sg0DSG5GBsLL5vT69v/Q+WJbSluRzzR/CZDiVTBV"
  valid-duration: 10 #in second
  refreshable-duration: 120 #in seconds